import type { Metadata } from "next";
import SEOLandingTemplate, { SEOLandingData } from "@/components/shared/SEOLandingTemplate";

export const metadata: Metadata = {
  title: "AI Text to Quiz Generator: Convert Plain Text into Tests | QuizGens",
  description: "Paste text articles, Notion notes, Claude summaries, or ChatGPT outputs to generate practice quizzes instantly with detailed reasoning.",
  alternates: {
    canonical: "https://quizgens.tech/text-to-quiz-generator",
  },
  openGraph: {
    title: "AI Text to Quiz Generator – Paste Plain Text to Test Yourself",
    description: "Easily convert copied text summaries, ChatGPT prompts, or web article paragraphs into interactive quizzes.",
    url: "https://quizgens.tech/text-to-quiz-generator",
  },
};

const pageData: SEOLandingData = {
  keyword: "Text to Quiz Generator",
  title: "Text to Quiz Generator",
  subtitle: "Copy and paste study summaries, web articles, or ChatGPT outputs directly to generate custom assessments instantly.",
  description: "Bypasses file upload flows. Paste text directly into a text area, see a real-time character limit check, and let Gemini AI create practice tests.",
  ctaText: "Convert Paste Text to Quiz Now",
  features: [
    {
      title: "Direct Clipboard Ingestion",
      desc: "Skip file conversion steps. Simply paste raw notes from Notion, Google Docs, or websites.",
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
        </svg>
      )
    },
    {
      title: "Newline-Aware Validation",
      desc: "Our character count checker ignores blank lines and enter keys to accurately validate actual content depth (300 - 6,000 characters).",
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
        </svg>
      )
    },
    {
      title: "Clean Document Folders",
      desc: "Pasted text quizzes are saved to your history log, but the raw text documents are hidden from your main directory to keep files neat.",
      icon: (
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
        </svg>
      )
    }
  ],
  faqs: [
    {
      q: "What is the minimum character length required?",
      a: "The pasted text must contain at least 300 characters (excluding newlines) to provide the AI model with sufficient context."
    },
    {
      q: "Can I paste content written by ChatGPT?",
      a: "Yes. Paste summaries, definitions, or study notes generated by external LLMs to convert them into structured test items."
    },
    {
      q: "Where is my pasted text saved?",
      a: "The raw text is stored as a document in Supabase Storage to satisfy active recall history lookups, but is filtered out of your main files panel so it does not clutter your workspace."
    }
  ],
  benefits: [
    {
      title: "Bypass File Preparation Steps",
      desc: "No need to compile notes into a PDF. Copy from Notion, paste, configure, and generate."
    },
    {
      title: "Fact-Check External Summaries",
      desc: "Verify if summaries match your actual textbook logic by generating reasoning on pasted text blocks."
    }
  ],
  targetAudience: [
    {
      title: "Notion & Docs Users",
      desc: "Students who organize text outlines inside cloud documents and want quick self-tests."
    },
    {
      title: "Web Researchers",
      desc: "Read a long article online, paste sections, and check key comprehension points immediately."
    },
    {
      title: "Language Students",
      desc: "Paste vocabulary texts or translation transcripts and generate fill-in-the-blank cards."
    }
  ],
  howItWorksSteps: [
    { step: "1", title: "Copy Notes", desc: "Select text summaries from cloud files, Notion pages, or web articles." },
    { step: "2", title: "Paste Text", desc: "Navigate to the Paste Text tab and input the clipboard text." },
    { step: "3", title: "Review Count", desc: "Ensure the text is between 300 and 6,000 characters." },
    { step: "4", title: "Start Quiz", desc: "Select options, click generate, and practice instantly." }
  ],
  relatedLinks: [
    { name: "AI Quiz Generator", href: "/ai-quiz-generator" },
    { name: "PDF to MCQ Generator", href: "/pdf-to-mcq-generator" },
    { name: "Image to Quiz Generator", href: "/image-to-quiz-generator" },
    { name: "MCQ Generator", href: "/mcq-generator" }
  ],
  relatedBlogs: [
    { name: "Create Quiz from Text Guide", href: "/blog/create-quiz-from-text" },
    { name: "AI Quiz Generator vs ChatGPT", href: "/blog/ai-quiz-generator-vs-chatgpt" }
  ]
};

export default function Page() {
  return <SEOLandingTemplate data={pageData} />;
}
